### ISSUE TITLE
Working with underlying with other value than 1.

### ISSUE THREAD

**Issue by MasterKenobi7** [luphord/longstaff_schwartz#2] opened 2021-05-01 13:25 UTC
* Longstaff-Schwartz Algorithm version:
* Python version:
* Operating System:

### Description

I tried to compute the American call price of an option on real data. The value of the stock price was not 1, so I tried to change the formula of the geometric Brownian motion. The simulated price(s) look nice and plausible. The problem arises when I try to use the "longstaff_schwartz_iter" & the "longstaff_schwartz" functions.

### What I Did

I ran the function "longstaff_schwartz" with the edited geometric Brownian motion as input. The code rises an error at the line
"continuation = fitted(x)" -  TypeError: 'numpy.ndarray' object is not callable

I tried to fix this issue for several hours without success. Is there another way to compute the price of an American option with a value <> 1 with these functions? All support would be highly appreciated!

**Comment by luphord** [comment] 2021-05-01 20:44
Can you upload your code somewhere or just paste it here? It's hard to tell what causes the error without seeing the code.

I doubt it has anything to do with the stock price. More likely that something is wrong with your `fit` function. What exactly did you pass in for `fit`?

**Comment by MasterKenobi7** [comment] 2021-05-02 08:25
Yes, of course, sorry!
`import numpy as np
from numpy.polynomial import Polynomial
from scipy.stats.distributions import norm, lognorm, rv_frozen

# Model parameters
n = 1000  # number of simulated paths
t = np.linspace(0, 1, n)  # timegrid for simulation
r = 0.011  # riskless rate
sigma = 0.16  # annual volatility of underlying
S = 10600 # initial stock price S0
strike = 10000


class GeometricBrownianMotion:
    '''Geometric Brownian Motion.(with optional drift).'''
    def __init__(self, mu: float = 0.0, sigma: float = 1.0):
        self.mu = mu
        self.sigma = sigma

    def simulate(self, t: np.array, n: int, rnd: np.random.RandomState) \
            -> np.array:
        assert t.ndim == 1, 'One dimensional time vector required'
        assert t.size > 0, 'At least one time point is required'
        dt = np.concatenate((t[0:1], np.diff(t)))
        assert (dt >= 0).all(), 'Increasing time vector required'
        # transposed simulation for automatic broadcasting
        dW = (rnd.normal(size=(t.size, n)).T * np.sqrt(dt)).T
        W = np.cumsum(dW, axis=0)
        return S* (np.exp(self.sigma * W.T + (self.mu - self.sigma**2 / 2) * t).T) #Multplying with S to get forcasts for price S

    def distribution(self, t: float) -> rv_frozen:
        mu_t = (self.mu - self.sigma**2/2) * t
        sigma_t = self.sigma * np.sqrt(t)
        return lognorm(scale=np.exp(mu_t), s=sigma_t)

def longstaff_schwartz_iter(X, t, df, fit, exercise_payoff,
                            itm_select=None):
    # given no prior exercise we just receive the final payoff
    cashflow = exercise_payoff(X[-1, :])
    # iterating backwards in time
    for i in reversed(range(1, X.shape[0] - 1)):
        # discount cashflows from next period
        cashflow = cashflow * df(t[i], t[i+1])
        x = X[i, :]
        # exercise value for time t[i]
        exercise = exercise_payoff(x)
        # boolean index of all in-the-money paths
        # (paths considered for exercise)
        itm = itm_select(exercise, x) \
            if itm_select \
            else np.full(x.shape, True)
        # fit curve
        fitted = fit(x[itm], cashflow[itm])
        # approximate continuation value
        continuation = fitted(x)
        # boolean index where exercise is beneficial
        ex_idx = itm & (exercise > continuation)
        # update cashflows with early exercises
        cashflow[ex_idx] = exercise[ex_idx]

        yield cashflow, x, fitted, continuation, exercise, ex_idx


def longstaff_schwartz(X, t, df, fit, exercise_payoff, itm_select=None):
    for cashflow, *_ in longstaff_schwartz_iter(X, t, df, fit,
                                                exercise_payoff, itm_select):
        pass
    return cashflow.mean(axis=0) * df(t[0], t[1])    
    
    
# Simulate the underlying
gbm = GeometricBrownianMotion(mu=r, sigma=sigma)
rnd = np.random.RandomState(7)
x = gbm.simulate(t, n, rnd)  # x.shape == (t.size, n)

def put_payoff(spot):
    return np.maximum(strike - spot, 0.0)

# Discount factor function
def constant_rate_df(t_from, t_to):
    return np.exp(-r * (t_to - t_from))

# Approximation of continuation value
def fit_quadratic(x, y):
    return np.polynomial.Polynomial.fit(x, y, 2, rcond=None)

# Selection of paths to consider for exercise
# (and continuation value approxmation)
def itm(payoff, spot):
    return payoff > 0

# Run valuation of American put option
npv_american = longstaff_schwartz(x, t, constant_rate_df,
                                  fit_quadratic, put_payoff, itm)

# European put option for comparison
npv_european = constant_rate_df(t[0], t[-1]) * put_payoff(x[-1]).mean()

# Check results
print(npv_american)
print(npv_european)
assert npv_american > npv_european`

When I run the code, the error occurring is:
"LinAlgError: SVD did not converge in Linear Least Squares"

When I change the variable "t" to "t = np.linspace(0, 2, n)", the error occurring is:
ValueError: Coefficient array is empty

Do you see any reason for the problem? Many thanks in advance!

**Comment by luphord** [comment] 2021-05-03 17:07
So the error you mentioned before is now gone, but you get two new ones?

Please refactor your code such that you call into the library instead of duplicating its functionality. For me it is relevant to see whether a) there is a bug in the library or b) your invocation is wrong. If you copy/paste/adapt the library code, that is hard for me to tell.

**Comment by MasterKenobi7** [comment] 2021-05-03 18:41
``Sorry, I duplicated its functionality with the intention to implement a price of the underlying. Because I do not see a way to do this with the library (maybe I overlooked something if this is the case I'm sorry). 

So, if I run this code:
```
import numpy as np
from numpy.polynomial import Polynomial
from scipy.stats.distributions import norm, lognorm, rv_frozen

from longstaff_schwartz.algorithm import longstaff_schwartz
from longstaff_schwartz.stochastic_process import GeometricBrownianMotion

# Model parameters
n = 1000  # number of simulated paths
t = np.linspace(0, 5, n)  # timegrid for simulation
r = 0.011  # riskless rate
sigma = 0.16  # annual volatility of underlying
#S = 10600 # initial stock price S0
strike = 10000

# Simulate the underlying
gbm = GeometricBrownianMotion(mu=r, sigma=sigma)
rnd = np.random.RandomState(7)
x = gbm.simulate(t, n, rnd)  # x.shape == (t.size, n)

def put_payoff(spot):
    return np.maximum(strike - spot, 0.0)

# Discount factor function
def constant_rate_df(t_from, t_to):
    return np.exp(-r * (t_to - t_from))

# Approximation of continuation value
def fit_quadratic(x, y):
    return np.polynomial.Polynomial.fit(x, y, 2, rcond=None)

# Selection of paths to consider for exercise
# (and continuation value approxmation)
def itm(payoff, spot):
    return payoff > 0

# Run valuation of American put option
npv_american = longstaff_schwartz(x, t, constant_rate_df,
                                  fit_quadratic, put_payoff, itm)

# European put option for comparison
npv_european = constant_rate_df(t[0], t[-1]) * put_payoff(x[-1]).mean()

# Check results
print(npv_american)
print(npv_european)
assert npv_american > npv_european
```
No error message occurs. But the problem is that the geometric Brownian motion does not take the underlying price into account. Do you have an idea how to do this?

Many thanks for your help, I really appreciate it.

**Comment by luphord** [comment] 2021-05-03 19:56
In order to employ the desired spot price you could multiply the result of `gbm.simulate(...)` with the spot:
`x = gbm.simulate(t, n, rnd) * 10600  # line 19 above`

If I make this modification to your code above, I run into numerical instabilities. The reason is that you chose a very high number of timesteps (1000) while only using 1000 paths. That combined with the fact that your option is out-of-the-money will cause "empty" regression steps and fail.

I suggest you reduce the number of timesteps, e.g. `t = np.linspace(0, 5, 250)  # line 10 above` roughly corresponding to a weekly grid. With that second modification, your code above runs and gives `992` for the American option and `934` for the European option. The analytical Black-Scholes price of the European put is `927`, so this does not look too far off.

**Comment by Jay-Bariya** [comment] 2021-05-04 07:24
I ran into the same problem. If the option is way out of money, it either returns SVD did not converge or coefficient array is empty. I want the code to return NA if either of error is raised. Here's my code:

`from longstaff_schwartz.algorithm import longstaff_schwartz
from longstaff_schwartz.stochastic_process import GeometricBrownianMotion
import numpy as np

# Model parameters
t = np.linspace(0, 5, 250)  # timegrid for simulation
r = 0.01  # riskless rate
sigma = 0.25  # annual volatility of underlying
n = 1000  # number of simulated paths
spot = 322
option_type = "call"

# Simulate the underlying
gbm = GeometricBrownianMotion(mu=r, sigma=sigma)
rnd = np.random.RandomState(10)
x = gbm.simulate(t, n, rnd)  # x.shape == (t.size, n)
x = spot*x

# Payoff (exercise) function
strike = 290

def option_payoff(spot):
    if(option_type == "put"):
        return np.maximum(strike - spot, 0.0)
    if(option_type == "call"):
        return np.maximum(spot - strike, 0.0)
        

# Discount factor function
def constant_rate_df(t_from, t_to):
    return np.exp(-r * (t_to - t_from))

# Approximation of continuation value
def fit_quadratic(x, y):
    return np.polynomial.Polynomial.fit(x, y, 2, rcond=None)

# Selection of paths to consider for exercise
# (and continuation value approxmation)
def itm(payoff, spot):
    return payoff > 0

# Run valuation of American put option
npv_american = longstaff_schwartz(x, t, constant_rate_df,
                                  fit_quadratic, option_payoff, itm)

# European put option for comparison
npv_european = constant_rate_df(t[0], t[-1]) * option_payoff(x[-1]).mean()

# Check results
print(npv_american)
print(npv_european)
if (option_type == "put"):
    assert npv_american > npv_european
if (option_type == "call"):
    print("Early excercise of American call option is not favorable when the underlying does not pay dividends")`

**Comment by Jay-Bariya** [comment] 2021-05-04 07:30
I ran in the same problem as mentioned above. If option is way out of money, it will raise non-convergence error or coefficient is empty. How do I resolve this? Can I define a function that returns NA values  if convergence fails ? 

Thank You
 

```
from longstaff_schwartz.algorithm import longstaff_schwartz
from longstaff_schwartz.stochastic_process import GeometricBrownianMotion
import numpy as np

# Model parameters
t = np.linspace(0, 5, 250)  # timegrid for simulation
r = 0.01  # riskless rate
sigma = 0.25  # annual volatility of underlying
n = 1000  # number of simulated paths
spot = 322
option_type = "call"

# Simulate the underlying
gbm = GeometricBrownianMotion(mu=r, sigma=sigma)
rnd = np.random.RandomState(10)
x = gbm.simulate(t, n, rnd)  # x.shape == (t.size, n)
x = spot*x

# Payoff (exercise) function
strike = 290

def option_payoff(spot):
    if(option_type == "put"):
        return np.maximum(strike - spot, 0.0)
    if(option_type == "call"):
        return np.maximum(spot - strike, 0.0)
        

# Discount factor function
def constant_rate_df(t_from, t_to):
    return np.exp(-r * (t_to - t_from))

# Approximation of continuation value
def fit_quadratic(x, y):
    return np.polynomial.Polynomial.fit(x, y, 2, rcond=None)

# Selection of paths to consider for exercise
# (and continuation value approxmation)
def itm(payoff, spot):
    return payoff > 0

# Run valuation of American put option
npv_american = longstaff_schwartz(x, t, constant_rate_df,
                                  fit_quadratic, option_payoff, itm)

# European put option for comparison
npv_european = constant_rate_df(t[0], t[-1]) * option_payoff(x[-1]).mean()

# Check results
print(npv_american)
print(npv_european)
if (option_type == "put"):
    assert npv_american > npv_european
if (option_type == "call"):
    print("Early excercise of American call option is not favorable when the underlying does not pay dividends")
```

**Comment by luphord** [comment] 2021-05-04 16:55
You could skip the selection of paths for regression altogether and use all paths instead. That is achieved by simply *not* passing `itm` to `longstaff_schwartz` or, more explicitly, by passing `itm_select=None`.

If you do this, *all* paths will be used for regression in all timesteps, regardless of whether they are in-the-money or not. The downside is that the approximation of continuation value becomes worse. In fact, the continuation value for an option can even be negative and the algorithm will prefer to execute the option for a payoff of 0. As a consequence, the value of an American put may be lower than the value of the corresponding European put.

If anyone has better ideas, I am very happy to hear them!

**Comment by luphord** [comment] 2021-06-10 14:25
@MasterKenobi7, @Jay-Bariya  Is there any further interest into this issue? Otherwise, I am going to close it.

**Comment by MasterKenobi7** [comment] 2021-06-10 14:43
@luphord Your answer helped me, thank you very much! So, the issue can be closed.
I‘m curious about another thing. Do you have any idea why the function (when applied to call options) spitts out rather too small option values im comparison to the binomial tree or Black Scholes model?

**Comment by luphord** [comment] 2021-07-29 16:20
@MasterKenobi7 I do not have an exact understanding of the effect here. But I can say for sure that American *Call* Options in a plain vanilla Black-Scholes-Model would not be exercised before maturity (see e.g. [The Black-Scholes Model, between 11.17 and 11.18](http://sfb649.wiwi.hu-berlin.de/fedc_homepage/xplore/tutorials/xlghtmlnode62.html)).

My guess then is, that due to approximation error of the continuation value, the algorithm would suggest early exercise anyway. That would result in sub-optimal exercise strategy and hence reduced value. What do you think?

**Comment by MasterKenobi7** [comment] 2021-07-29 19:48
@luphord Yes, this makes sense. I also found this paper (Couffignals, E. (2010) Quasi-Monte Carlo simulations for Longstaff Schwartz pricing of american options Dissertation, University of Oxford, Oxford. ) which also looks at this issue. Thanks again for your support!

**Closed** 2021-08-02 15:14 UTC
